### ISSUE TITLE
Google Font Not Loading

### ISSUE THREAD

**Issue by birksy89** [cwlsn/gatsby-simple-contentful-starter#5]
Sorry if this isn't a bug or issue with your specific implementation... I'm using your starter as a way of learning GraphQL/ Gatsby / Styled Components etc - And I'm not sure where the responsibilities of each lie...

I've just got round to pushing my test site 🎉 
https://awesome-roentgen-54ad7a.netlify.com/

And I noticed that the Google font doesn't load - I checked yours, in case I'd broken something and it seems to also not load the "Quicksand" font
https://gatsby-simple-contentful-starter.netlify.com/

On mine, it seems to actually work if you navigate from one page to another...

On closer inspection it appears to load the font when I hover over the "Insta" link:
![hover](https://user-images.githubusercontent.com/4971630/51389724-25987880-1b25-11e9-8a61-5284c0a0d59f.PNG)

Just trying to understand what's going on here - If you could point me in the right direction, I'd be grateful.

Thanks again for all your work on this 👍

**Comment by cwlsn** [comment]
Hey, I think I know what's going on here. I'll try to push out a fix soon!
